name             'paladinci'
maintainer       'Paladin Software'
maintainer_email 'ole@paladinsoftware.com'
license          'All rights reserved'
description      'Installs/Configures paladin-ci'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'user'
depends          'openssh'
depends          'ssh-keys'
depends          'ssh_known_hosts'
